# configs/config.yaml
data:
  path: "data"

model:
  k: 20
  dropout: 0.5

training:
  epochs: 2
  batch_size: 1
  learning_rate: 0.01
  checkpoint_dir: "checkpoints/"

evaluation:
  metrics:
    - "mse"
    - "mae"