# configs/config.yaml
data:
  path: "data"
  subject: "Abram"
  demographic: "novice"

model:
  k: 20
  dropout: 0.5

training:
  epochs: 1
  batch_size: 1
  learning_rate: 0.0001
  checkpoint_dir: "checkpoints/"

evaluation:
  metrics:
    - "mse"