# configs/config.yaml
data:
  path: "data"
  subject: "subject1"
  demographic: "novice"

model:
  k: 20
  dropout: 0.5

training:
  epochs: 3
  batch_size: 1
  learning_rate: 0.001
  checkpoint_dir: "checkpoints/"

evaluation:
  metrics:
    - "mse"