# configs/config.yaml
data:
  path: "data"
  subject: "Abram"
  demographic: "novice"

model:
  k: 15
  dropout: 0.7
  ordinal_weights: [1.0, 1.2, 1.5, 1.8, 2.0]
  focal_gamma: 2.0

training:
  epochs: 1
  batch_size: 1
  learning_rate: 0.0001
  checkpoint_dir: "checkpoints/"

evaluation:
  metrics:
    - "mse"