# configs/config.yaml
data:
  path: "data"
  subject_type: "novice"  # Options: "novice" or "expert"
  subject_id: "1"         # Options: "1", "2", "3"
  config_type: "eeg"       # Options: "et", "eeg"

model:
  k: 12
  dropout: 0.0
  gamma: 2.0

training:
  epochs: 3
  batch_size: 1
  learning_rate: 0.0003
  checkpoint_dir: "checkpoints/"

evaluation:
  metrics:
    - "mse"