# configs/config.yaml
data:
  path: "data"
  subject: "abram"
  demographic: "novice"

model:
  k: 12
  dropout: 0.0

training:
  epochs: 50
  batch_size: 1
  learning_rate: 0.0003
  checkpoint_dir: "checkpoints/"

evaluation:
  metrics:
    - "mse"