data:
  config_type: eeg
  path: data
  subject_id: '1'
  subject_type: novice
evaluation:
  metrics:
  - mse
model:
  dropout: 0.0
  gamma: 2.0
  k: 12
training:
  batch_size: 1
  checkpoint_dir: checkpoints/
  epochs: 3
  learning_rate: 0.0003
